language: python

addons:
  hosts:
  - authomatic.com

before_install:
- openssl aes-256-cbc -K $encrypted_cd197f1c301c_key -iv $encrypted_cd197f1c301c_iv
  -in tests/functional_tests/config.py.enc -out tests/functional_tests/config.py -d

install: pip install flask liveandletdie>=0.0.4 selenium pyopenssl python-openid

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar
- java -jar selenium-server-standalone-2.46.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &

script: PYTHONPATH=. py.test -vs tests/functional_tests/
