language: objective-c
addons:
  hosts:
  - authomatic.com
install: pip install tox
script: tox -e py27
after_failure: tail -n 1000000 tests/*.log
before_install:
- openssl aes-256-cbc -K $encrypted_5fa87d13797d_key -iv $encrypted_5fa87d13797d_iv
  -in tests/functional_tests/config.py.enc -out tests/functional_tests/config.py -d
- brew update
- brew install caskroom/cask/brew-cask
- brew cask install google-chrome
