language: python
addons:
  hosts:
  - authomatic.com
before_install:
- openssl aes-256-cbc -K $encrypted_cd197f1c301c_key -iv $encrypted_cd197f1c301c_iv
  -in tests/functional_tests/config.py.enc -out tests/functional_tests/config.py -d
install: pip install tox
script: tox
after_script: tail -n 1000000 tests/functional_tests/*.log
