language: objective-c
addons:
  hosts:
  - authomatic.test
  - authomatic.com
  - authomatic.org
install: sudo pip install tox
script: sudo tox -e py34 -- -vv --tb=no
after_failure:
- tail -n 1000000 tests/functional_tests/*.log
- tail -n 1000000 tests/*.log
before_install:
- openssl aes-256-cbc -K $encrypted_5fa87d13797d_key -iv $encrypted_5fa87d13797d_iv
  -in tests/functional_tests/config.py.enc -out tests/functional_tests/config.py -d
- brew update
- brew install caskroom/cask/brew-cask
- sudo brew cask install google-chrome
- brew install python3
